name: Windows tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  windows:
    name: Windows Py${{ matrix.PYTHON_VERSION }} spyder-from-${{ matrix.SPYDER_SOURCE }}
    runs-on: windows-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      RUNNER_OS: 'windows'
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['3.10']        
        SPYDER_SOURCE: ['git']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
           activate-environment: test
           auto-update-conda: true
           auto-activate-base: false
           python-version: ${{ matrix.PYTHON_VERSION }}
           channels: conda-forge/label/spyder_kernels_rc,conda-forge,defaults
           channel-priority: strict
           miniforge-variant: Mambaforge
      - name: Checkout Spyder from git
        if: matrix.SPYDER_SOURCE == 'git'
        uses: actions/checkout@v3
        with:
          repository: 'spyder-ide/spyder'
          path: 'spyder'
      - name: Install Spyder's dependencies (main)
        if: matrix.SPYDER_SOURCE == 'git'
        shell: bash -l {0}
        run: conda env update --file spyder/requirements/main.yml
      - name: Install Spyder from source
        if: matrix.SPYDER_SOURCE == 'git'
        shell: bash -l {0}
        run: pip install -e spyder
      - name: Install package dependencies (without Spyder)
        if: matrix.SPYDER_SOURCE == 'git'
        shell: bash -l {0}
        run: |
          python .github/scripts/generate-without-spyder.py
          conda install --file requirements/without-spyder.txt -y
      - name: Install package dependencies
        if: matrix.SPYDER_SOURCE == 'conda'
        shell: bash -l {0}
        run: conda install --file requirements/conda.txt -y -q -c conda-forge
      - name: Install test dependencies
        shell: bash -l {0}
        run: conda install -c spyder-ide --file requirements/tests.txt -y -q
      - name: Install Package
        shell: bash -l {0}
        run: pip install --no-deps -e .
      - name: Show environment information
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: pytest kite_provider -vv
